### ISSUE TITLE
Could not find dependency 'play'

### ISSUE THREAD

**Issue by ishangupta-1510** [Cabbache/OmegleMITM#2]

**Comment by Cabbache** [comment]
Hi there, the dependency is called 'SoX - Sound eXchange, the Swiss Army knife of audio manipulation'. When you install it, you get the 'play' command.

Try install it with 'sudo apt-get install sox libsox-fmt-all', if it doesn't work check for packages with 'sudo apt search sox'.

Reference guide: https://linuxg.net/how-to-install-sox-14-4-2-sound-exchange-sound-processing-program-on-ubuntu-and-derivative-systems/

**Comment by ishangupta-1510** [comment]
Thanks for the response 
Now I am getting this error
Unable to open V4L2 device '/dev/video4'
Could not write header for output file #0 (incorrect codec parameters ?): No such file or directory
Error initializing output stream 0:0 -- 
[video4linux2,v4l2 @ 0x7f6754000cc0] Cannot open video device /dev/video4: No such file or directory
/dev/video4: No such file or directory
55

**Comment by Cabbache** [comment]
Can you open another issue on this?
